#!/usr/bin/env python3

import sys
from os import path

import argparse

import blobTrace

parser = argparse.ArgumentParser(description='Track juggling.')
parser.add_argument('filename', metavar='FILE', help='the video file to run the tracking algorithm on')
parser.add_argument('-f', '--frame', type=int, default=0, help='the index of the frame of the video to start rendering on')
args = parser.parse_args()

if not args.filename.endswith('.mp4'):
    # Append video extension.
    args.filename += '.mp4'

if not path.exists(args.filename):
    # Append the video folder if they just gave a filename.
    args.filename = f'test_vids/{args.filename}'
    if not path.exists(args.filename):
        print(f'Video file "{args.filename}" not found.', file=sys.stderr)
        sys.exit(1)

print(f'Loading video "{args.filename}".')

try:
    blobTrace.trace(args.filename, startingFrame=args.frame)
except KeyboardInterrupt:
    import cv2
    cv2.destroyAllWindows()
